#!/bin/bash

set -e

if [ -z $TOOLS ]; then
	echo "You haven't set 'TOOLS' variable."
	exit 1
fi

if [ -z $ROOTFS ]; then
	echo "You haven't set 'ROOTFS' variable."
	exit 1
fi

export CWD="$(pwd)"
export STUFF="$CWD/stuff"
export OUT="$CWD/out"
export SRC="$OUT/src"

export RUSTVER="1.34.2"

case $BARCH in
	x86_64)
		export XHOST="x86_64-linux-musl"
		export XTARGET="x86_64-unknown-linux-musl"
		;;
	aarch64)
		export XHOST="aarch64-linux-musl"
		export XTARGET="aarch64-unknown-linux-musl"
		;;
	armv7l)
		export XHOST="arm-linux-musleabihf"
		export XTARGET="armv7-unknown-linux-musleabihf"
		;;
	armv6l)
		export XHOST="arm-linux-musleabihf"
		export XTARGET="arm-unknown-linux-musleabihf"
		;;
	mips)
		export XHOST="mips-linux-musl"
		export XTARGET="mips-unknown-linux-musl"
		;;
	mipsel)
		export XHOST="mipsel-linux-musl"
		export XTARGET="mipsel-unknown-linux-musl"
		;;
	ppc64le)
		export XHOST="powerpc64le-linux-musl"
		export XTARGET="powerpc64le-unknown-linux-musl"
		;;
	ppc64)
		export XHOST="powerpc64-linux-musl"
		export XTARGET="powerpc64-unknown-linux-musl"
		;;
	ppc)
		export XHOST="powerpc64-linux-musl"
		export XTARGET="powerpc64-unknown-linux-musl"
		;;
	*)
		echo "Architecture is not set or is not supported by 'bootstrap' script"
		exit 1
esac

export LC_ALL="POSIX"
export PATH="$TOOLS/bin:$PATH"
export HOSTCC="gcc"
export HOSTCXX="g++"

if [ -z $MKJOBS ]; then
	export MKJOBS="$(expr $(nproc) + 1)"
fi

export MKOPTS="-j$MKJOBS"

rm -rf $OUT
mkdir -p $SRC

cd $SRC
wget https://static.rust-lang.org/dist/rustc-$RUSTVER-src.tar.gz
tar -xvf rustc-$RUSTVER-src.tar.gz
cd rustc-$RUSTVER-src
patch -Np1 -i $STUFF/musl-and-security.patch

cat << EOF > config.toml
[llvm]
optimize = true
release-debuginfo = false
assertions = false
static-libstdcpp = true
ninja = true
targets = "AArch64;ARM;Mips;PowerPC;Sparc;X86"
experimental-targets = ""

[build]
host = [
  "$XHOST"
]
target = [
  "$XTARGET"
]
cargo = "$(which cargo)"
rustc = "$(which rustc)"
docs = false
compiler-docs = false
submodules = false
full-bootstrap = false
extended = true
verbose = 0
sanitizers = false
profiler = false
vendor = true

[rust]
optimize = true
codegen-units = 1
debug-assertions = false
debuginfo = false
debuginfo-lines = false
jemalloc = false
backtrace = true
default-linker = "gcc"
channel = "stable"
rpath = true

[dist]
src-tarball = false

[target.$XTARGET]
cc = "$XHOST-gcc"
cxx = "$XHOST-g++"
linker = "$XHOST-gcc"
EOF

export MUSL_ROOT=$ROOTFS/usr
export RUST_BACKTRACE=1
export RUSTFLAGS="-C linker=$XHOST-gcc"

./x.py dist $MKOPTS
