#!/bin/bash

set -e

clear_vendor_checksums() {
	sed -i 's/\("files":{\)[^}]*/\1/' vendor/$1/.cargo-checksum.json
}

mktoolchain() {
	case $1 in
		armv7)
			make $MKOPTS TARGET=arm-linux-musleabihf GCC_CONFIG="--with-arch=armv7-a --with-fpu=vfpv3-d16"
			make $MKOPTS OUTPUT=/opt/rustie TARGET=arm-linux-musleabihf GCC_CONFIG="--with-arch=armv7-a --with-fpu=vfpv3-d16" install
			;;
		*)
			make $MKOPTS TARGET=$i-linux-musl
			make $MKOPTS OUTPUT=/opt/rustie TARGET=$i-linux-musl install
			;;
	esac
}

export CWD="$(pwd)"
export STUFF="$CWD/stuff"
export OUT="$CWD/out"
export SRC="$OUT/src"
export TOOLS="$OUT/tools"

export RUSTVER="1.42.0"

export LC_ALL="POSIX"
export HOSTCC="gcc"
export HOSTCXX="g++"
export XHOST="$(echo ${MACHTYPE} | sed -e 's/-[^-]*/-cross/')"
export PATH="/opt/rustie/bin:$PATH"

if [ -z $MKOPTS ]; then
	export MKJOBS="$(expr $(nproc) + 1)"
fi

export MKOPTS="-j$MKJOBS"

rm -rf $OUT
mkdir -p $SRC $TOOLS

if [ "$TOOLCHAIN" != "no" ]; then
	cd $SRC
	git clone https://github.com/richfelker/musl-cross-make.git --depth 1
	cd musl-cross-make

	for i in x86_64 i586 aarch64 armv7 powerpc64le powerpc64 powerpc; do
		mktoolchain $i
	done

	cd $SRC
	wget https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.0.2.tar.gz
	tar -xvf libressl-3.0.2.tar.gz
	for i in x86_64-linux-musl i586-linux-musl aarch64-linux-musl arm-linux-musleabihf powerpc64le-linux-musl powerpc64-linux-musl powerpc-linux-musl; do
		cd $SRC/libressl-3.0.2
		mkdir build-$i
		cd build-$i
		CFLAGS="-fPIE -Os -g0 -s -pipe" \
		../configure \
			--build=$XHOST \
			--host=$i \
			--prefix=/opt/rustie/$i \
			--disable-shared
		make $MKOPTS
		make $MKOPTS install
	done
fi

cd $SRC
wget https://static.rust-lang.org/dist/rustc-$RUSTVER-src.tar.gz
tar -xvf rustc-$RUSTVER-src.tar.gz
cd rustc-$RUSTVER-src
patch -Np1 -i $STUFF/musl.patch
patch -Np1 -i $STUFF/need-ssp_nonshared.patch
patch -Np1 -i $STUFF/0006-Prefer-libgcc_eh-over-libunwind-musl.patch
patch -Np1 -i $STUFF/0001-openssl-src-add-Ataraxia-s-targets.patch
patch -Np1 -i $STUFF/static-pie.patch
clear_vendor_checksums libc
clear_vendor_checksums openssl-src

cat << EOF > config.toml
[llvm]
optimize = true
release-debuginfo = false
assertions = false
static-libstdcpp = true
ninja = true
targets = "AArch64;ARM;X86;PowerPC"
experimental-targets = ""

[build]
host = [
  "x86_64-unknown-linux-musl",
  "i586-unknown-linux-musl",
  "aarch64-unknown-linux-musl",
  "armv7-unknown-linux-musleabihf",
  "powerpc64le-unknown-linux-musl",
  "powerpc64-unknown-linux-musl",
  "powerpc-unknown-linux-musl"
]
cargo = "$(which cargo)"
rustc = "$(which rustc)"
docs = false
compiler-docs  = false
extended = true
submodules = false
python = "python3"
locked-deps = true
vendor = true
cargo-native-static = true
sanitizers = false
profiler = false
full-bootstrap = false

[rust]
channel = "nightly"
rpath  = false
codegen-units = 1
debuginfo-level = 0
debug = false
backtrace = false
jemalloc = false
debug-assertions = false
codegen-tests = false

[target.x86_64-unknown-linux-musl]
cc = "x86_64-linux-musl-gcc"
cxx = "x86_64-linux-musl-g++"
linker = "x86_64-linux-musl-gcc"
musl-root = "/opt/rustie/x86_64-linux-musl"
crt-static = false

[target.i586-unknown-linux-musl]
cc = "i586-linux-musl-gcc"
cxx = "i586-linux-musl-g++"
linker = "i586-linux-musl-gcc"
musl-root = "/opt/rustie/i586-linux-musl"
crt-static = false

[target.aarch64-unknown-linux-musl]
cc = "aarch64-linux-musl-gcc"
cxx = "aarch64-linux-musl-g++"
linker = "aarch64-linux-musl-gcc"
musl-root = "/opt/rustie/aarch64-linux-musl"
crt-static = false

[target.armv7-unknown-linux-musleabihf]
cc = "arm-linux-musleabihf-gcc"
cxx = "arm-linux-musleabihf-g++"
linker = "arm-linux-musleabihf-gcc"
musl-root = "/opt/rustie/arm-linux-musleabihf"
crt-static = false

[target.powerpc64le-unknown-linux-musl]
cc = "powerpc64le-linux-musl-gcc"
cxx = "powerpc64le-linux-musl-g++"
linker = "powerpc64le-linux-musl-gcc"
musl-root = "/opt/rustie/powerpc64le-linux-musl"
crt-static = false

[target.powerpc64-unknown-linux-musl]
cc = "powerpc64-linux-musl-gcc"
cxx = "powerpc64-linux-musl-g++"
linker = "powerpc64-linux-musl-gcc"
musl-root = "/opt/rustie/powerpc64-linux-musl"
crt-static = false

[target.powerpc-unknown-linux-musl]
cc = "powerpc-linux-musl-gcc"
cxx = "powerpc-linux-musl-g++"
linker = "powerpc-linux-musl-gcc"
musl-root = "/opt/rustie/powerpc-linux-musl"
crt-static = false
EOF

export RUST_BACKTRACE=1
export X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="/opt/rustie/x86_64-linux-musl"
export I586_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="/opt/rustie/i586-linux-musl"
export AARCH64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="/opt/rustie/aarch64-linux-musl"
export ARMV7L_UNKNOWN_LINUX_MUSLEABIHF_OPENSSL_DIR="/opt/rustie/arm-linux-musleabihf"
export POWERPC64LE_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="/opt/rustie/powerpc64le-linux-musl"
export POWERPC64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="/opt/rustie/powerpc64-linux-musl"
export POWERPC_UNKNOWN_LINUX_MUSL_OPENSSL_DIR="/opt/rustie/powerpc-linux-musl"

./x.py dist -j$MKJOBS
